export let countries = [
	{ name: "Afghanistan", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png", code: "+93" },
	{ name: "Åland Islands", flag: "https://flagcdn.com/w320/ax.png", code: "+3" },
	{ name: "Albania", flag: "https://flagcdn.com/w320/al.png", code: "+355" },
	{ name: "Algeria", flag: "https://flagcdn.com/w320/dz.png", code: "+213" },
	{ name: "American Samoa", flag: "https://flagcdn.com/w320/as.png", code: "+1" },
	{ name: "Andorra", flag: "https://flagcdn.com/w320/ad.png", code: "+376" },
	{ name: "Angola", flag: "https://flagcdn.com/w320/ao.png", code: "+244" },
	{ name: "Anguilla", flag: "https://flagcdn.com/w320/ai.png", code: "+1" },
	{ name: "Antarctica", flag: "https://flagcdn.com/w320/aq.png", code: "+672" },
	{ name: "Antigua and Barbuda", flag: "https://flagcdn.com/w320/ag.png", code: "+1" },
	{ name: "Argentina", flag: "https://flagcdn.com/w320/ar.png", code: "+54" },
	{ name: "Armenia", flag: "https://flagcdn.com/w320/am.png", code: "+374" },
	{ name: "Aruba", flag: "https://flagcdn.com/w320/aw.png", code: "+297" },
	{ name: "Australia", flag: "https://flagcdn.com/w320/au.png", code: "+61" },
	{ name: "Austria", flag: "https://flagcdn.com/w320/at.png", code: "+43" },
	{ name: "Azerbaijan", flag: "https://flagcdn.com/w320/az.png", code: "+994" },
	{ name: "Bahamas", flag: "https://flagcdn.com/w320/bs.png", code: "+1" },
	{ name: "Bahrain", flag: "https://flagcdn.com/w320/bh.png", code: "+973" },
	{ name: "Bangladesh", flag: "https://flagcdn.com/w320/bd.png", code: "+880" },
	{ name: "Barbados", flag: "https://flagcdn.com/w320/bb.png", code: "+1" },
	{ name: "Belarus", flag: "https://flagcdn.com/w320/by.png", code: "+375" },
	{ name: "Belgium", flag: "https://flagcdn.com/w320/be.png", code: "+32" },
	{ name: "Belize", flag: "https://flagcdn.com/w320/bz.png", code: "+501" },
	{ name: "Benin", flag: "https://flagcdn.com/w320/bj.png", code: "+229" },
	{ name: "Bermuda", flag: "https://flagcdn.com/w320/bm.png", code: "+1" },
	{ name: "Bhutan", flag: "https://flagcdn.com/w320/bt.png", code: "+975" },
	{ name: "Bolivia", flag: "https://flagcdn.com/w320/bo.png", code: "+591" },
	{ name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w320/ba.png", code: "+387" },
	{ name: "Botswana", flag: "https://flagcdn.com/w320/bw.png", code: "+267" },
	{ name: "Bouvet Island", flag: "https://flagcdn.com/w320/bv.png", code: "+55" },
	{ name: "Brazil", flag: "https://flagcdn.com/w320/br.png", code: "+55" },
	{ name: "British Indian Ocean Territory", flag: "https://flagcdn.com/w320/io.png", code: "+246" },
	{ name: "British Virgin Islands", flag: "https://flagcdn.com/w320/vg.png", code: "+1" },
	{ name: "Brunei", flag: "https://flagcdn.com/w320/bn.png", code: "+673" },
	{ name: "Bulgaria", flag: "https://flagcdn.com/w320/bg.png", code: "+359" },
	{ name: "Burkina Faso", flag: "https://flagcdn.com/w320/bf.png", code: "+226" },
	{ name: "Burundi", flag: "https://flagcdn.com/w320/bi.png", code: "+257" },
	{ name: "Cambodia", flag: "https://flagcdn.com/w320/kh.png", code: "+855" },
	{ name: "Cameroon", flag: "https://flagcdn.com/w320/cm.png", code: "+237" },
	{ name: "Canada", flag: "https://flagcdn.com/w320/ca.png", code: "+1" },
	{ name: "Cape Verde", flag: "https://flagcdn.com/w320/cv.png", code: "+238" },
	{ name: "Caribbean Netherlands", flag: "https://flagcdn.com/w320/bq.png", code: "+599" },
	{ name: "Cayman Islands", flag: "https://flagcdn.com/w320/ky.png", code: "+1" },
	{ name: "Central African Republic", flag: "https://flagcdn.com/w320/cf.png", code: "+236" },
	{ name: "Chad", flag: "https://flagcdn.com/w320/td.png", code: "+235" },
	{ name: "Chile", flag: "https://flagcdn.com/w320/cl.png", code: "+56" },
	{ name: "China", flag: "https://flagcdn.com/w320/cn.png", code: "+86" },
	{ name: "Christmas Island", flag: "https://flagcdn.com/w320/cx.png", code: "+61" },
	{ name: "Cocos (Keeling) Islands", flag: "https://flagcdn.com/w320/cc.png", code: "+61" },
	{ name: "Colombia", flag: "https://flagcdn.com/w320/co.png", code: "+57" },
	{ name: "Comoros", flag: "https://flagcdn.com/w320/km.png", code: "+269" },
	{ name: "Cook Islands", flag: "https://flagcdn.com/w320/ck.png", code: "+682" },
	{ name: "Costa Rica", flag: "https://flagcdn.com/w320/cr.png", code: "+506" },
	{ name: "Croatia", flag: "https://flagcdn.com/w320/hr.png", code: "+385" },
	{ name: "Cuba", flag: "https://flagcdn.com/w320/cu.png", code: "+53" },
	{ name: "Curaçao", flag: "https://flagcdn.com/w320/cw.png", code: "+599" },
	{ name: "Cyprus", flag: "https://flagcdn.com/w320/cy.png", code: "+357" },
	{ name: "Czechia", flag: "https://flagcdn.com/w320/cz.png", code: "+420" },
	{ name: "Denmark", flag: "https://flagcdn.com/w320/dk.png", code: "+45" },
	{ name: "Djibouti", flag: "https://flagcdn.com/w320/dj.png", code: "+253" },
	{ name: "Dominica", flag: "https://flagcdn.com/w320/dm.png", code: "+1" },
	{ name: "Dominican Republic", flag: "https://flagcdn.com/w320/do.png", code: "+1" },
	{ name: "DR Congo", flag: "https://flagcdn.com/w320/cd.png", code: "+243" },
	{ name: "Ecuador", flag: "https://flagcdn.com/w320/ec.png", code: "+593" },
	{ name: "Egypt", flag: "https://flagcdn.com/w320/eg.png", code: "+20" },
	{ name: "El Salvador", flag: "https://flagcdn.com/w320/sv.png", code: "+503" },
	{ name: "Equatorial Guinea", flag: "https://flagcdn.com/w320/gq.png", code: "+240" },
	{ name: "Eritrea", flag: "https://flagcdn.com/w320/er.png", code: "+291" },
	{ name: "Estonia", flag: "https://flagcdn.com/w320/ee.png", code: "+372" },
	{ name: "Eswatini", flag: "https://flagcdn.com/w320/sz.png", code: "+268" },
	{ name: "Ethiopia", flag: "https://flagcdn.com/w320/et.png", code: "+251" },
	{ name: "Falkland Islands", flag: "https://flagcdn.com/w320/fk.png", code: "+500" },
	{ name: "Faroe Islands", flag: "https://flagcdn.com/w320/fo.png", code: "+298" },
	{ name: "Fiji", flag: "https://flagcdn.com/w320/fj.png", code: "+679" },
	{ name: "Finland", flag: "https://flagcdn.com/w320/fi.png", code: "+358" },
	{ name: "France", flag: "https://flagcdn.com/w320/fr.png", code: "+33" },
	{ name: "French Guiana", flag: "https://flagcdn.com/w320/gf.png", code: "+594" },
	{ name: "French Polynesia", flag: "https://flagcdn.com/w320/pf.png", code: "+689" },
	{ name: "French Southern and Antarctic Lands", flag: "https://flagcdn.com/w320/tf.png", code: "+262" },
	{ name: "Gabon", flag: "https://flagcdn.com/w320/ga.png", code: "+241" },
	{ name: "Gambia", flag: "https://flagcdn.com/w320/gm.png", code: "+220" },
	{ name: "Georgia", flag: "https://flagcdn.com/w320/ge.png", code: "+995" },
	{ name: "Germany", flag: "https://flagcdn.com/w320/de.png", code: "+49" },
	{ name: "Ghana", flag: "https://flagcdn.com/w320/gh.png", code: "+233" },
	{ name: "Gibraltar", flag: "https://flagcdn.com/w320/gi.png", code: "+350" },
	{ name: "Greece", flag: "https://flagcdn.com/w320/gr.png", code: "+30" },
	{ name: "Greenland", flag: "https://flagcdn.com/w320/gl.png", code: "+299" },
	{ name: "Grenada", flag: "https://flagcdn.com/w320/gd.png", code: "+1" },
	{ name: "Guadeloupe", flag: "https://flagcdn.com/w320/gp.png", code: "+590" },
	{ name: "Guam", flag: "https://flagcdn.com/w320/gu.png", code: "+1" },
	{ name: "Guatemala", flag: "https://flagcdn.com/w320/gt.png", code: "+502" },
	{ name: "Guernsey", flag: "https://flagcdn.com/w320/gg.png", code: "+44" },
	{ name: "Guinea", flag: "https://flagcdn.com/w320/gn.png", code: "+224" },
	{ name: "Guinea-Bissau", flag: "https://flagcdn.com/w320/gw.png", code: "+245" },
	{ name: "Guyana", flag: "https://flagcdn.com/w320/gy.png", code: "+592" },
	{ name: "Haiti", flag: "https://flagcdn.com/w320/ht.png", code: "+509" },
	{ name: "Heard Island and McDonald Islands", flag: "https://flagcdn.com/w320/hm.png", code: "+672" },
	{ name: "Honduras", flag: "https://flagcdn.com/w320/hn.png", code: "+504" },
	{ name: "Hong Kong", flag: "https://flagcdn.com/w320/hk.png", code: "+852" },
	{ name: "Hungary", flag: "https://flagcdn.com/w320/hu.png", code: "+36" },
	{ name: "Iceland", flag: "https://flagcdn.com/w320/is.png", code: "+354" },
	{ name: "India", flag: "https://flagcdn.com/w320/in.png", code: "+91" },
	{ name: "Indonesia", flag: "https://flagcdn.com/w320/id.png", code: "+62" },
	{ name: "Iran", flag: "https://flagcdn.com/w320/ir.png", code: "+98" },
	{ name: "Iraq", flag: "https://flagcdn.com/w320/iq.png", code: "+964" },
	{ name: "Ireland", flag: "https://flagcdn.com/w320/ie.png", code: "+353" },
	{ name: "Isle of Man", flag: "https://flagcdn.com/w320/im.png", code: "+44" },
	{ name: "Israel", flag: "https://flagcdn.com/w320/il.png", code: "+972" },
	{ name: "Italy", flag: "https://flagcdn.com/w320/it.png", code: "+39" },
	{ name: "Ivory Coast", flag: "https://flagcdn.com/w320/ci.png", code: "+225" },
	{ name: "Jamaica", flag: "https://flagcdn.com/w320/jm.png", code: "+1" },
	{ name: "Japan", flag: "https://flagcdn.com/w320/jp.png", code: "+81" },
	{ name: "Jersey", flag: "https://flagcdn.com/w320/je.png", code: "+44" },
	{ name: "Jordan", flag: "https://flagcdn.com/w320/jo.png", code: "+962" },
	{ name: "Kazakhstan", flag: "https://flagcdn.com/w320/kz.png", code: "+7" },
	{ name: "Kenya", flag: "https://flagcdn.com/w320/ke.png", code: "+254" },
	{ name: "Kiribati", flag: "https://flagcdn.com/w320/ki.png", code: "+686" },
	{ name: "Kosovo", flag: "https://flagcdn.com/w320/xk.png", code: "+383" },
	{ name: "Kuwait", flag: "https://flagcdn.com/w320/kw.png", code: "+965" },
	{ name: "Kyrgyzstan", flag: "https://flagcdn.com/w320/kg.png", code: "+996" },
	{ name: "Laos", flag: "https://flagcdn.com/w320/la.png", code: "+856" },
	{ name: "Latvia", flag: "https://flagcdn.com/w320/lv.png", code: "+371" },
	{ name: "Lebanon", flag: "https://flagcdn.com/w320/lb.png", code: "+961" },
	{ name: "Lesotho", flag: "https://flagcdn.com/w320/ls.png", code: "+266" },
	{ name: "Liberia", flag: "https://flagcdn.com/w320/lr.png", code: "+231" },
	{ name: "Libya", flag: "https://flagcdn.com/w320/ly.png", code: "+218" },
	{ name: "Liechtenstein", flag: "https://flagcdn.com/w320/li.png", code: "+423" },
	{ name: "Lithuania", flag: "https://flagcdn.com/w320/lt.png", code: "+370" },
	{ name: "Luxembourg", flag: "https://flagcdn.com/w320/lu.png", code: "+352" },
	{ name: "Macau", flag: "https://flagcdn.com/w320/mo.png", code: "+853" },
	{ name: "Madagascar", flag: "https://flagcdn.com/w320/mg.png", code: "+261" },
	{ name: "Malawi", flag: "https://flagcdn.com/w320/mw.png", code: "+265" },
	{ name: "Malaysia", flag: "https://flagcdn.com/w320/my.png", code: "+60" },
	{ name: "Maldives", flag: "https://flagcdn.com/w320/mv.png", code: "+960" },
	{ name: "Mali", flag: "https://flagcdn.com/w320/ml.png", code: "+223" },
	{ name: "Malta", flag: "https://flagcdn.com/w320/mt.png", code: "+356" },
	{ name: "Marshall Islands", flag: "https://flagcdn.com/w320/mh.png", code: "+692" },
	{ name: "Martinique", flag: "https://flagcdn.com/w320/mq.png", code: "+596" },
	{ name: "Mauritania", flag: "https://flagcdn.com/w320/mr.png", code: "+222" },
	{ name: "Mauritius", flag: "https://flagcdn.com/w320/mu.png", code: "+230" },
	{ name: "Mayotte", flag: "https://flagcdn.com/w320/yt.png", code: "+262" },
	{ name: "Mexico", flag: "https://flagcdn.com/w320/mx.png", code: "+52" },
	{ name: "Micronesia", flag: "https://flagcdn.com/w320/fm.png", code: "+691" },
	{ name: "Moldova", flag: "https://flagcdn.com/w320/md.png", code: "+373" },
	{ name: "Monaco", flag: "https://flagcdn.com/w320/mc.png", code: "+377" },
	{ name: "Mongolia", flag: "https://flagcdn.com/w320/mn.png", code: "+976" },
	{ name: "Montenegro", flag: "https://flagcdn.com/w320/me.png", code: "+382" },
	{ name: "Montserrat", flag: "https://flagcdn.com/w320/ms.png", code: "+1" },
	{ name: "Morocco", flag: "https://flagcdn.com/w320/ma.png", code: "+212" },
	{ name: "Mozambique", flag: "https://flagcdn.com/w320/mz.png", code: "+258" },
	{ name: "Myanmar", flag: "https://flagcdn.com/w320/mm.png", code: "+95" },
	{ name: "Namibia", flag: "https://flagcdn.com/w320/na.png", code: "+264" },
	{ name: "Nauru", flag: "https://flagcdn.com/w320/nr.png", code: "+674" },
	{ name: "Nepal", flag: "https://flagcdn.com/w320/np.png", code: "+977" },
	{ name: "Netherlands", flag: "https://flagcdn.com/w320/nl.png", code: "+31" },
	{ name: "New Caledonia", flag: "https://flagcdn.com/w320/nc.png", code: "+687" },
	{ name: "New Zealand", flag: "https://flagcdn.com/w320/nz.png", code: "+64" },
	{ name: "Nicaragua", flag: "https://flagcdn.com/w320/ni.png", code: "+505" },
	{ name: "Niger", flag: "https://flagcdn.com/w320/ne.png", code: "+227" },
	{ name: "Nigeria", flag: "https://flagcdn.com/w320/ng.png", code: "+234" },
	{ name: "Niue", flag: "https://flagcdn.com/w320/nu.png", code: "+683" },
	{ name: "Norfolk Island", flag: "https://flagcdn.com/w320/nf.png", code: "+672" },
	{ name: "North Korea", flag: "https://flagcdn.com/w320/kp.png", code: "+850" },
	{ name: "North Macedonia", flag: "https://flagcdn.com/w320/mk.png", code: "+389" },
	{ name: "Northern Mariana Islands", flag: "https://flagcdn.com/w320/mp.png", code: "+1" },
	{ name: "Norway", flag: "https://flagcdn.com/w320/no.png", code: "+47" },
	{ name: "Oman", flag: "https://flagcdn.com/w320/om.png", code: "+968" },
	{ name: "Pakistan", flag: "https://flagcdn.com/w320/pk.png", code: "+92" },
	{ name: "Palau", flag: "https://flagcdn.com/w320/pw.png", code: "+680" },
	{ name: "Palestine", flag: "https://flagcdn.com/w320/ps.png", code: "+970" },
	{ name: "Panama", flag: "https://flagcdn.com/w320/pa.png", code: "+507" },
	{ name: "Papua New Guinea", flag: "https://flagcdn.com/w320/pg.png", code: "+675" },
	{ name: "Paraguay", flag: "https://flagcdn.com/w320/py.png", code: "+595" },
	{ name: "Peru", flag: "https://flagcdn.com/w320/pe.png", code: "+51" },
	{ name: "Philippines", flag: "https://flagcdn.com/w320/ph.png", code: "+63" },
	{ name: "Pitcairn Islands", flag: "https://flagcdn.com/w320/pn.png", code: "+64" },
	{ name: "Poland", flag: "https://flagcdn.com/w320/pl.png", code: "+48" },
	{ name: "Portugal", flag: "https://flagcdn.com/w320/pt.png", code: "+351" },
	{ name: "Puerto Rico", flag: "https://flagcdn.com/w320/pr.png", code: "+1" },
	{ name: "Qatar", flag: "https://flagcdn.com/w320/qa.png", code: "+974" },
	{ name: "Republic of the Congo", flag: "https://flagcdn.com/w320/cg.png", code: "+242" },
	{ name: "Réunion", flag: "https://flagcdn.com/w320/re.png", code: "+262" },
	{ name: "Romania", flag: "https://flagcdn.com/w320/ro.png", code: "+40" },
	{ name: "Russia", flag: "https://flagcdn.com/w320/ru.png", code: "+7" },
	{ name: "Rwanda", flag: "https://flagcdn.com/w320/rw.png", code: "+250" },
	{ name: "Saint Barthélemy", flag: "https://flagcdn.com/w320/bl.png", code: "+590" },
	{ name: "Saint Helena, Ascension and Tristan da Cunha", flag: "https://flagcdn.com/w320/sh.png", code: "+2" },
	{ name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/w320/kn.png", code: "+1" },
	{ name: "Saint Lucia", flag: "https://flagcdn.com/w320/lc.png", code: "+1" },
	{ name: "Saint Martin", flag: "https://flagcdn.com/w320/mf.png", code: "+590" },
	{ name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/w320/pm.png", code: "+508" },
	{ name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/w320/vc.png", code: "+1" },
	{ name: "Samoa", flag: "https://flagcdn.com/w320/ws.png", code: "+685" },
	{ name: "San Marino", flag: "https://flagcdn.com/w320/sm.png", code: "+378" },
	{ name: "São Tomé and Príncipe", flag: "https://flagcdn.com/w320/st.png", code: "+239" },
	{ name: "Saudi Arabia", flag: "https://flagcdn.com/w320/sa.png", code: "+966" },
	{ name: "Senegal", flag: "https://flagcdn.com/w320/sn.png", code: "+221" },
	{ name: "Serbia", flag: "https://flagcdn.com/w320/rs.png", code: "+381" },
	{ name: "Seychelles", flag: "https://flagcdn.com/w320/sc.png", code: "+248" },
	{ name: "Sierra Leone", flag: "https://flagcdn.com/w320/sl.png", code: "+232" },
	{ name: "Singapore", flag: "https://flagcdn.com/w320/sg.png", code: "+65" },
	{ name: "Sint Maarten", flag: "https://flagcdn.com/w320/sx.png", code: "+721" },
	{ name: "Slovakia", flag: "https://flagcdn.com/w320/sk.png", code: "+421" },
	{ name: "Slovenia", flag: "https://flagcdn.com/w320/si.png", code: "+386" },
	{ name: "Solomon Islands", flag: "https://flagcdn.com/w320/sb.png", code: "+677" },
	{ name: "Somalia", flag: "https://flagcdn.com/w320/so.png", code: "+252" },
	{ name: "South Africa", flag: "https://flagcdn.com/w320/za.png", code: "+27" },
	{ name: "South Georgia", flag: "https://flagcdn.com/w320/gs.png", code: "+500" },
	{ name: "South Korea", flag: "https://flagcdn.com/w320/kr.png", code: "+82" },
	{ name: "South Sudan", flag: "https://flagcdn.com/w320/ss.png", code: "+211" },
	{ name: "Spain", flag: "https://flagcdn.com/w320/es.png", code: "+34" },
	{ name: "Sri Lanka", flag: "https://flagcdn.com/w320/lk.png", code: "+94" },
	{ name: "Sudan", flag: "https://flagcdn.com/w320/sd.png", code: "+249" },
	{ name: "Suriname", flag: "https://flagcdn.com/w320/sr.png", code: "+597" },
	{ name: "Svalbard and Jan Mayen", flag: "https://flagcdn.com/w320/sj.png", code: "+4" },
	{ name: "Sweden", flag: "https://flagcdn.com/w320/se.png", code: "+46" },
	{ name: "Switzerland", flag: "https://flagcdn.com/w320/ch.png", code: "+41" },
	{ name: "Syria", flag: "https://flagcdn.com/w320/sy.png", code: "+963" },
	{ name: "Taiwan", flag: "https://flagcdn.com/w320/tw.png", code: "+886" },
	{ name: "Tajikistan", flag: "https://flagcdn.com/w320/tj.png", code: "+992" },
	{ name: "Tanzania", flag: "https://flagcdn.com/w320/tz.png", code: "+255" },
	{ name: "Thailand", flag: "https://flagcdn.com/w320/th.png", code: "+66" },
	{ name: "Timor-Leste", flag: "https://flagcdn.com/w320/tl.png", code: "+670" },
	{ name: "Togo", flag: "https://flagcdn.com/w320/tg.png", code: "+228" },
	{ name: "Tokelau", flag: "https://flagcdn.com/w320/tk.png", code: "+690" },
	{ name: "Tonga", flag: "https://flagcdn.com/w320/to.png", code: "+676" },
	{ name: "Trinidad and Tobago", flag: "https://flagcdn.com/w320/tt.png", code: "+1" },
	{ name: "Tunisia", flag: "https://flagcdn.com/w320/tn.png", code: "+216" },
	{ name: "Turkey", flag: "https://flagcdn.com/w320/tr.png", code: "+90" },
	{ name: "Turkmenistan", flag: "https://flagcdn.com/w320/tm.png", code: "+993" },
	{ name: "Turks and Caicos Islands", flag: "https://flagcdn.com/w320/tc.png", code: "+1" },
	{ name: "Tuvalu", flag: "https://flagcdn.com/w320/tv.png", code: "+688" },
	{ name: "Uganda", flag: "https://flagcdn.com/w320/ug.png", code: "+256" },
	{ name: "Ukraine", flag: "https://flagcdn.com/w320/ua.png", code: "+380" },
	{ name: "United Arab Emirates", flag: "https://flagcdn.com/w320/ae.png", code: "+971" },
	{ name: "United Kingdom", flag: "https://flagcdn.com/w320/gb.png", code: "+44" },
	{ name: "United States", flag: "https://flagcdn.com/w320/us.png", code: "+1" },
	{ name: "United States Minor Outlying Islands", flag: "https://flagcdn.com/w320/um.png", code: "+268" },
	{ name: "United States Virgin Islands", flag: "https://flagcdn.com/w320/vi.png", code: "+1" },
	{ name: "Uruguay", flag: "https://flagcdn.com/w320/uy.png", code: "+598" },
	{ name: "Uzbekistan", flag: "https://flagcdn.com/w320/uz.png", code: "+998" },
	{ name: "Vanuatu", flag: "https://flagcdn.com/w320/vu.png", code: "+678" },
	{ name: "Vatican City", flag: "https://flagcdn.com/w320/va.png", code: "+3" },
	{ name: "Venezuela", flag: "https://flagcdn.com/w320/ve.png", code: "+58" },
	{ name: "Vietnam", flag: "https://flagcdn.com/w320/vn.png", code: "+84" },
	{ name: "Wallis and Futuna", flag: "https://flagcdn.com/w320/wf.png", code: "+681" },
	{ name: "Western Sahara", flag: "https://flagcdn.com/w320/eh.png", code: "+2" },
	{ name: "Yemen", flag: "https://flagcdn.com/w320/ye.png", code: "+967" },
	{ name: "Zambia", flag: "https://flagcdn.com/w320/zm.png", code: "+260" },
	{ name: "Zimbabwe", flag: "https://flagcdn.com/w320/zw.png", code: "+263" },
];
